### ISSUE TITLE
USER STORY: Wireframing the Website

### ISSUE THREAD

**Issue by raycarter23** [raycarter23/film-buzz#2]
As a **developer** I can **get an idea of the whole design system** so that **I can work on the UI/UX design**

### Acceptance Criteria

- [x] Creating all of the wireframes through Figma

### Tasks

- [x] Brainstorm a list of features to go on the website
- [x] Analyse existing Movie blog websites for design inspiration
- [x] Use Dribble for additional UI design inspiration
- [x] Design low-fidelity wireframes for the main pages
